export const countryList = [
  {
    value: "AF",
    label: "Afghanistan",
    dial_code: "+93",
    image: "/4x3/af.svg",
  },
  {
    value: "AL",
    label: "Albania",
    dial_code: "+355",
    image: "/4x3/al.svg",
  },
  {
    value: "DZ",
    label: "Algeria",
    dial_code: "+213",
    image: "/4x3/dz.svg",
  },
  {
    value: "AS",
    label: "American Samoa",
    dial_code: "+1-684",
    image: "/4x3/as.svg",
  },
  {
    value: "AD",
    label: "Andorra",
    dial_code: "+376",
    image: "/4x3/ad.svg",
  },
  {
    value: "AO",
    label: "Angola",
    dial_code: "+244",
    image: "/4x3/ao.svg",
  },
  {
    value: "AI",
    label: "Anguilla",
    dial_code: "+1-264",
    image: "/4x3/ai.svg",
  },
  {
    value: "AQ",
    label: "Antarctica",
    dial_code: "+",
    image: "/4x3/aq.svg",
  },
  {
    value: "AG",
    label: "Antigua and Barbuda",
    dial_code: "+1-268",
    image: "/4x3/ag.svg",
  },
  {
    value: "AR",
    label: "Argentina",
    dial_code: "+54",
    image: "/4x3/ar.svg",
  },
  {
    value: "AM",
    label: "Armenia",
    dial_code: "+374",
    image: "/4x3/am.svg",
  },
  {
    value: "AW",
    label: "Aruba",
    dial_code: "+297",
    image: "/4x3/aw.svg",
  },
  {
    value: "AU",
    label: "Australia",
    dial_code: "+61",
    image: "/4x3/au.svg",
  },
  {
    value: "AT",
    label: "Austria",
    dial_code: "+43",
    image: "/4x3/at.svg",
  },
  {
    value: "AZ",
    label: "Azerbaijan",
    dial_code: "+994",
    image: "/4x3/az.svg",
  },
  {
    value: "BS",
    label: "Bahamas",
    dial_code: "+1-242",
    image: "/4x3/bs.svg",
  },
  {
    value: "BH",
    label: "Bahrain",
    dial_code: "+973",
    image: "/4x3/bh.svg",
  },
  {
    value: "BD",
    label: "Bangladesh",
    dial_code: "+880",
    image: "/4x3/bd.svg",
  },
  {
    value: "BB",
    label: "Barbados",
    dial_code: "+1-246",
    image: "/4x3/bb.svg",
  },
  {
    value: "BY",
    label: "Belarus",
    dial_code: "+375",
    image: "/4x3/by.svg",
  },
  {
    value: "BE",
    label: "Belgium",
    dial_code: "+32",
    image: "/4x3/be.svg",
  },
  {
    value: "BZ",
    label: "Belize",
    dial_code: "+501",
    image: "/4x3/bz.svg",
  },
  {
    value: "BJ",
    label: "Benin",
    dial_code: "+229",
    image: "/4x3/bj.svg",
  },
  {
    value: "BM",
    label: "Bermuda",
    dial_code: "+1-441",
    image: "/4x3/bm.svg",
  },
  {
    value: "BT",
    label: "Bhutan",
    dial_code: "+975",
    image: "/4x3/bt.svg",
  },
  {
    value: "BO",
    label: "Bolivia",
    dial_code: "+591",
    image: "/4x3/bo.svg",
  },
  {
    value: "BQ",
    label: "Caribbean Netherlands",
    dial_code: "+599",
    image: "/4x3/bq.svg",
  },
  {
    value: "BA",
    label: "Bosnia and Herzegovina",
    dial_code: "+387",
    image: "/4x3/ba.svg",
  },
  {
    value: "BW",
    label: "Botswana",
    dial_code: "+267",
    image: "/4x3/bw.svg",
  },
  {
    value: "BR",
    label: "Brazil",
    dial_code: "+55",
    image: "/4x3/br.svg",
  },
  {
    value: "IO",
    label: "British Indian Ocean Territory",
    dial_code: "+246",
    image: "/4x3/io.svg",
  },
  {
    value: "BN",
    label: "Brunei Darussalam",
    dial_code: "+673",
    image: "/4x3/bn.svg",
  },
  {
    value: "BG",
    label: "Bulgaria",
    dial_code: "+359",
    image: "/4x3/bg.svg",
  },
  {
    value: "BF",
    label: "Burkina Faso",
    dial_code: "+226",
    image: "/4x3/bf.svg",
  },
  {
    value: "BI",
    label: "Burundi",
    dial_code: "+257",
    image: "/4x3/bi.svg",
  },
  {
    value: "KH",
    label: "Cambodia",
    dial_code: "+855",
    image: "/4x3/kh.svg",
  },
  {
    value: "CM",
    label: "Cameroon",
    dial_code: "+237",
    image: "/4x3/cm.svg",
  },
  {
    value: "CA",
    label: "Canada",
    dial_code: "+1",
    image: "/4x3/ca.svg",
  },
  {
    value: "CV",
    label: "Cape Verde",
    dial_code: "+238",
    image: "/4x3/cv.svg",
  },
  {
    value: "KY",
    label: "Cayman Islands",
    dial_code: "+1-345",
    image: "/4x3/ky.svg",
  },
  {
    value: "CF",
    label: "Central African Republic",
    dial_code: "+236",
    image: "/4x3/cf.svg",
  },
  {
    value: "TD",
    label: "Chad",
    dial_code: "+235",
    image: "/4x3/td.svg",
  },
  {
    value: "CL",
    label: "Chile",
    dial_code: "+56",
    image: "/4x3/cl.svg",
  },
  {
    value: "CN",
    label: "China",
    dial_code: "+86",
    image: "/4x3/cn.svg",
  },
  {
    value: "CX",
    label: "Christmas Island",
    dial_code: "+61",
    image: "/4x3/cx.svg",
  },
  {
    value: "CC",
    label: "Cocos (Keeling) Islands",
    dial_code: "+61",
    image: "/4x3/cc.svg",
  },
  {
    value: "CO",
    label: "Colombia",
    dial_code: "+57",
    image: "/4x3/co.svg",
  },
  {
    value: "KM",
    label: "Comoros",
    dial_code: "+269",
    image: "/4x3/km.svg",
  },
  {
    value: "CG",
    label: "Congo",
    dial_code: "+242",
    image: "/4x3/cg.svg",
  },
  {
    value: "CD",
    label: "Congo",
    dial_code: "+243",
    image: "/4x3/cd.svg",
  },
  {
    value: "CK",
    label: "Cook Islands",
    dial_code: "+682",
    image: "/4x3/ck.svg",
  },
  {
    value: "CR",
    label: "Costa Rica",
    dial_code: "+506",
    image: "/4x3/cr.svg",
  },
  {
    value: "HR",
    label: "Croatia",
    dial_code: "+385",
    image: "/4x3/hr.svg",
  },
  {
    value: "CU",
    label: "Cuba",
    dial_code: "+53",
    image: "/4x3/cu.svg",
  },
  {
    value: "CW",
    label: "Curaçao",
    dial_code: "+599",
    image: "/4x3/cw.svg",
  },
  {
    value: "CY",
    label: "Cyprus",
    dial_code: "+357",
    image: "/4x3/cy.svg",
  },
  {
    value: "CZ",
    label: "Czech Republic",
    dial_code: "+420",
    image: "/4x3/cz.svg",
  },
  {
    value: "CI",
    label: "Côte d'Ivoire",
    dial_code: "+225",
    image: "/4x3/ci.svg",
  },
  {
    value: "DK",
    label: "Denmark",
    dial_code: "+45",
    image: "/4x3/dk.svg",
  },
  {
    value: "DJ",
    label: "Djibouti",
    dial_code: "+253",
    image: "/4x3/dj.svg",
  },
  {
    value: "DM",
    label: "Dominica",
    dial_code: "+1-767",
    image: "/4x3/dm.svg",
  },
  {
    value: "DO",
    label: "Dominican Republic",
    dial_code: "+1-809",
    image: "/4x3/do.svg",
  },
  {
    value: "EC",
    label: "Ecuador",
    dial_code: "+593",
    image: "/4x3/ec.svg",
  },
  {
    value: "EG",
    label: "Egypt",
    dial_code: "+20",
    image: "/4x3/eg.svg",
  },
  {
    value: "SV",
    label: "El Salvador",
    dial_code: "+503",
    image: "/4x3/sv.svg",
  },
  {
    value: "GQ",
    label: "Equatorial Guinea",
    dial_code: "+240",
    image: "/4x3/gq.svg",
  },
  {
    value: "ER",
    label: "Eritrea",
    dial_code: "+291",
    image: "/4x3/er.svg",
  },
  {
    value: "EE",
    label: "Estonia",
    dial_code: "+372",
    image: "/4x3/ee.svg",
  },
  {
    value: "ET",
    label: "Ethiopia",
    dial_code: "+251",
    image: "/4x3/et.svg",
  },
  {
    value: "FK",
    label: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    image: "/4x3/fk.svg",
  },
  {
    value: "FO",
    label: "Faroe Islands",
    dial_code: "+298",
    image: "/4x3/fo.svg",
  },
  {
    value: "FJ",
    label: "Fiji",
    dial_code: "+679",
    image: "/4x3/fj.svg",
  },
  {
    value: "FI",
    label: "Finland",
    dial_code: "+358",
    image: "/4x3/fi.svg",
  },
  {
    value: "FR",
    label: "France",
    dial_code: "+33",
    image: "/4x3/fr.svg",
  },
  {
    value: "GF",
    label: "French Guiana",
    dial_code: "+594",
    image: "/4x3/gf.svg",
  },
  {
    value: "PF",
    label: "French Polynesia",
    dial_code: "+689",
    image: "/4x3/pf.svg",
  },
  {
    value: "TF",
    label: "French Southern Territories",
    dial_code: "+",
    image: "/4x3/tf.svg",
  },
  {
    value: "GA",
    label: "Gabon",
    dial_code: "+241",
    image: "/4x3/ga.svg",
  },
  {
    value: "GM",
    label: "Gambia",
    dial_code: "+220",
    image: "/4x3/gm.svg",
  },
  {
    value: "GE",
    label: "Georgia",
    dial_code: "+995",
    image: "/4x3/ge.svg",
  },
  {
    value: "DE",
    label: "Germany",
    dial_code: "+49",
    image: "/4x3/de.svg",
  },
  {
    value: "GH",
    label: "Ghana",
    dial_code: "+233",
    image: "/4x3/gh.svg",
  },
  {
    value: "GI",
    label: "Gibraltar",
    dial_code: "+350",
    image: "/4x3/gi.svg",
  },
  {
    value: "GR",
    label: "Greece",
    dial_code: "+30",
    image: "/4x3/gr.svg",
  },
  {
    value: "GL",
    label: "Greenland",
    dial_code: "+299",
    image: "/4x3/gl.svg",
  },
  {
    value: "GD",
    label: "Grenada",
    dial_code: "+1-473",
    image: "/4x3/gd.svg",
  },
  {
    value: "GP",
    label: "Guadeloupe",
    dial_code: "+590",
    image: "/4x3/gp.svg",
  },
  {
    value: "GU",
    label: "Guam",
    dial_code: "+1-671",
    image: "/4x3/gu.svg",
  },
  {
    value: "GT",
    label: "Guatemala",
    dial_code: "+502",
    image: "/4x3/gt.svg",
  },
  {
    value: "GG",
    label: "Guernsey",
    dial_code: "+44-1481",
    image: "/4x3/gg.svg",
  },
  {
    value: "GN",
    label: "Guinea",
    dial_code: "+224",
    image: "/4x3/gn.svg",
  },
  {
    value: "GW",
    label: "Guinea-Bissau",
    dial_code: "+245",
    image: "/4x3/gw.svg",
  },
  {
    value: "GY",
    label: "Guyana",
    dial_code: "+592",
    image: "/4x3/gy.svg",
  },
  {
    value: "HT",
    label: "Haiti",
    dial_code: "+509",
    image: "/4x3/ht.svg",
  },
  {
    value: "VA",
    label: "Holy See (Vatican City State)",
    dial_code: "+379",
    image: "/4x3/va.svg",
  },
  {
    value: "HN",
    label: "Honduras",
    dial_code: "+504",
    image: "/4x3/hn.svg",
  },
  {
    value: "HK",
    label: "Hong Kong",
    dial_code: "+852",
    image: "/4x3/hk.svg",
  },
  {
    value: "HU",
    label: "Hungary",
    dial_code: "+36",
    image: "/4x3/hu.svg",
  },
  {
    value: "IS",
    label: "Iceland",
    dial_code: "+354",
    image: "/4x3/is.svg",
  },
  {
    value: "IN",
    label: "India",
    dial_code: "+91",
    image: "/4x3/in.svg",
  },
  {
    value: "ID",
    label: "Indonesia",
    dial_code: "+62",
    image: "/4x3/id.svg",
  },
  {
    value: "IR",
    label: "Iran",
    dial_code: "+98",
    image: "/4x3/ir.svg",
  },
  {
    value: "IQ",
    label: "Iraq",
    dial_code: "+964",
    image: "/4x3/iq.svg",
  },
  {
    value: "IE",
    label: "Ireland",
    dial_code: "+353",
    image: "/4x3/ie.svg",
  },
  {
    value: "IM",
    label: "Isle of Man",
    dial_code: "+44-1624",
    image: "/4x3/im.svg",
  },
  {
    value: "IL",
    label: "Israel",
    dial_code: "+972",
    image: "/4x3/il.svg",
  },
  {
    value: "IT",
    label: "Italy",
    dial_code: "+39",
    image: "/4x3/it.svg",
  },
  {
    value: "JM",
    label: "Jamaica",
    dial_code: "+1-876",
    image: "/4x3/jm.svg",
  },
  {
    value: "JP",
    label: "Japan",
    dial_code: "+81",
    image: "/4x3/jp.svg",
  },
  {
    value: "JE",
    label: "Jersey",
    dial_code: "+44-1534",
    image: "/4x3/je.svg",
  },
  {
    value: "JO",
    label: "Jordan",
    dial_code: "+962",
    image: "/4x3/jo.svg",
  },
  {
    value: "KZ",
    label: "Kazakhstan",
    dial_code: "+7",
    image: "/4x3/kz.svg",
  },
  {
    value: "KE",
    label: "Kenya",
    dial_code: "+254",
    image: "/4x3/ke.svg",
  },
  {
    value: "KI",
    label: "Kiribati",
    dial_code: "+686",
    image: "/4x3/ki.svg",
  },
  {
    value: "KP",
    label: "North Korea",
    dial_code: "+850",
    image: "/4x3/kp.svg",
  },
  {
    value: "KR",
    label: "South Korea",
    dial_code: "+82",
    image: "/4x3/kr.svg",
  },
  {
    value: "KW",
    label: "Kuwait",
    dial_code: "+965",
    image: "/4x3/kw.svg",
  },
  {
    value: "KG",
    label: "Kyrgyzstan",
    dial_code: "+996",
    image: "/4x3/kg.svg",
  },
  {
    value: "LA",
    label: "Laos",
    dial_code: "+856",
    image: "/4x3/la.svg",
  },
  {
    value: "LV",
    label: "Latvia",
    dial_code: "+371",
    image: "/4x3/lv.svg",
  },
  {
    value: "LB",
    label: "Lebanon",
    dial_code: "+961",
    image: "/4x3/lb.svg",
  },
  {
    value: "LS",
    label: "Lesotho",
    dial_code: "+266",
    image: "/4x3/ls.svg",
  },
  {
    value: "LR",
    label: "Liberia",
    dial_code: "+231",
    image: "/4x3/lr.svg",
  },
  {
    value: "LY",
    label: "Libya",
    dial_code: "+218",
    image: "/4x3/ly.svg",
  },
  {
    value: "LI",
    label: "Liechtenstein",
    dial_code: "+423",
    image: "/4x3/li.svg",
  },
  {
    value: "LT",
    label: "Lithuania",
    dial_code: "+370",
    image: "/4x3/lt.svg",
  },
  {
    value: "LU",
    label: "Luxembourg",
    dial_code: "+352",
    image: "/4x3/lu.svg",
  },
  {
    value: "MO",
    label: "Macao",
    dial_code: "+853",
    image: "/4x3/mo.svg",
  },
  {
    value: "MK",
    label: "Macedonia",
    dial_code: "+389",
    image: "/4x3/mk.svg",
  },
  {
    value: "MG",
    label: "Madagascar",
    dial_code: "+261",
    image: "/4x3/mg.svg",
  },
  {
    value: "MW",
    label: "Malawi",
    dial_code: "+265",
    image: "/4x3/mw.svg",
  },
  {
    value: "MY",
    label: "Malaysia",
    dial_code: "+60",
    image: "/4x3/my.svg",
  },
  {
    value: "MV",
    label: "Maldives",
    dial_code: "+960",
    image: "/4x3/mv.svg",
  },
  {
    value: "ML",
    label: "Mali",
    dial_code: "+223",
    image: "/4x3/ml.svg",
  },
  {
    value: "MT",
    label: "Malta",
    dial_code: "+356",
    image: "/4x3/mt.svg",
  },
  {
    value: "MH",
    label: "Marshall Islands",
    dial_code: "+692",
    image: "/4x3/mh.svg",
  },
  {
    value: "MQ",
    label: "Martinique",
    dial_code: "+596",
    image: "/4x3/mq.svg",
  },
  {
    value: "MR",
    label: "Mauritania",
    dial_code: "+222",
    image: "/4x3/mr.svg",
  },
  {
    value: "MU",
    label: "Mauritius",
    dial_code: "+230",
    image: "/4x3/mu.svg",
  },
  {
    value: "YT",
    label: "Mayotte",
    dial_code: "+262",
    image: "/4x3/yt.svg",
  },
  {
    value: "MX",
    label: "Mexico",
    dial_code: "+52",
    image: "/4x3/mx.svg",
  },
  {
    value: "FM",
    label: "Micronesia",
    dial_code: "+691",
    image: "/4x3/fm.svg",
  },
  {
    value: "MD",
    label: "Moldova",
    dial_code: "+373",
    image: "/4x3/md.svg",
  },
  {
    value: "MC",
    label: "Monaco",
    dial_code: "+377",
    image: "/4x3/mc.svg",
  },
  {
    value: "MN",
    label: "Mongolia",
    dial_code: "+976",
    image: "/4x3/mn.svg",
  },
  {
    value: "ME",
    label: "Montenegro",
    dial_code: "+382",
    image: "/4x3/me.svg",
  },
  {
    value: "MS",
    label: "Montserrat",
    dial_code: "+1-664",
    image: "/4x3/ms.svg",
  },
  {
    value: "MA",
    label: "Morocco",
    dial_code: "+212",
    image: "/4x3/ma.svg",
  },
  {
    value: "MZ",
    label: "Mozambique",
    dial_code: "+258",
    image: "/4x3/mz.svg",
  },
  {
    value: "MM",
    label: "Myanmar",
    dial_code: "+95",
    image: "/4x3/mm.svg",
  },
  {
    value: "NA",
    label: "Namibia",
    dial_code: "+264",
    image: "/4x3/na.svg",
  },
  {
    value: "NR",
    label: "Nauru",
    dial_code: "+674",
    image: "/4x3/nr.svg",
  },
  {
    value: "NP",
    label: "Nepal",
    dial_code: "+977",
    image: "/4x3/np.svg",
  },
  {
    value: "NL",
    label: "Netherlands",
    dial_code: "+31",
    image: "/4x3/nl.svg",
  },
  {
    value: "NC",
    label: "New Caledonia",
    dial_code: "+687",
    image: "/4x3/nc.svg",
  },
  {
    value: "NZ",
    label: "New Zealand",
    dial_code: "+64",
    image: "/4x3/nz.svg",
  },
  {
    value: "NI",
    label: "Nicaragua",
    dial_code: "+505",
    image: "/4x3/ni.svg",
  },
  {
    value: "NE",
    label: "Niger",
    dial_code: "+227",
    image: "/4x3/ne.svg",
  },
  {
    value: "NG",
    label: "Nigeria",
    dial_code: "+234",
    image: "/4x3/ng.svg",
  },
  {
    value: "NU",
    label: "Niue",
    dial_code: "+683",
    image: "/4x3/nu.svg",
  },
  {
    value: "NF",
    label: "Norfolk Island",
    dial_code: "+672",
    image: "/4x3/nf.svg",
  },
  {
    value: "MP",
    label: "Northern Mariana Islands",
    dial_code: "+1-670",
    image: "/4x3/mp.svg",
  },
  {
    value: "NO",
    label: "Norway",
    dial_code: "+47",
    image: "/4x3/no.svg",
  },
  {
    value: "OM",
    label: "Oman",
    dial_code: "+968",
    image: "/4x3/om.svg",
  },
  {
    value: "PK",
    label: "Pakistan",
    dial_code: "+92",
    image: "/4x3/pk.svg",
  },
  {
    value: "PW",
    label: "Palau",
    dial_code: "+680",
    image: "/4x3/pw.svg",
  },
  {
    value: "PS",
    label: "Palestine, State of",
    dial_code: "+970",
    image: "/4x3/ps.svg",
  },
  {
    value: "PA",
    label: "Panama",
    dial_code: "+507",
    image: "/4x3/pa.svg",
  },
  {
    value: "PG",
    label: "Papua New Guinea",
    dial_code: "+675",
    image: "/4x3/pg.svg",
  },
  {
    value: "PY",
    label: "Paraguay",
    dial_code: "+595",
    image: "/4x3/py.svg",
  },
  {
    value: "PE",
    label: "Peru",
    dial_code: "+51",
    image: "/4x3/pe.svg",
  },
  {
    value: "PH",
    label: "Philippines",
    dial_code: "+63",
    image: "/4x3/ph.svg",
  },
  {
    value: "PN",
    label: "Pitcairn",
    dial_code: "+870",
    image: "/4x3/pn.svg",
  },
  {
    value: "PL",
    label: "Poland",
    dial_code: "+48",
    image: "/4x3/pl.svg",
  },
  {
    value: "PT",
    label: "Portugal",
    dial_code: "+351",
    image: "/4x3/pt.svg",
  },
  {
    value: "PR",
    label: "Puerto Rico",
    dial_code: "+1-787",
    image: "/4x3/pr.svg",
  },
  {
    value: "QA",
    label: "Qatar",
    dial_code: "+974",
    image: "/4x3/qa.svg",
  },
  {
    value: "RO",
    label: "Romania",
    dial_code: "+40",
    image: "/4x3/ro.svg",
  },
  {
    value: "RU",
    label: "Russian Federation",
    dial_code: "+7",
    image: "/4x3/ru.svg",
  },
  {
    value: "RW",
    label: "Rwanda",
    dial_code: "+250",
    image: "/4x3/rw.svg",
  },
  {
    value: "RE",
    label: "Réunion",
    dial_code: "+262",
    image: "/4x3/re.svg",
  },
  {
    value: "BL",
    label: "Saint Barthélemy",
    dial_code: "+590",
    image: "/4x3/bl.svg",
  },
  {
    value: "SH",
    label: "St. Helena",
    dial_code: "+290",
    image: "/4x3/sh.svg",
  },
  {
    value: "KN",
    label: "St. Kitts and Nevis",
    dial_code: "+1-869",
    image: "/4x3/kn.svg",
  },
  {
    value: "LC",
    label: "St. Lucia",
    dial_code: "+1-758",
    image: "/4x3/lc.svg",
  },
  {
    value: "MF",
    label: "St. Martin",
    dial_code: "+590",
    image: "/4x3/mf.svg",
  },
  {
    value: "PM",
    label: "St. Pierre",
    dial_code: "+508",
    image: "/4x3/pm.svg",
  },
  {
    value: "VC",
    label: "St. Vincent",
    dial_code: "+1-784",
    image: "/4x3/vc.svg",
  },
  {
    value: "WS",
    label: "Samoa",
    dial_code: "+685",
    image: "/4x3/ws.svg",
  },
  {
    value: "SM",
    label: "San Marino",
    dial_code: "+378",
    image: "/4x3/sm.svg",
  },
  {
    value: "ST",
    label: "Sao Tome and Principe",
    dial_code: "+239",
    image: "/4x3/st.svg",
  },
  {
    value: "SA",
    label: "Saudi Arabia",
    dial_code: "+966",
    image: "/4x3/sa.svg",
  },
  {
    value: "SN",
    label: "Senegal",
    dial_code: "+221",
    image: "/4x3/sn.svg",
  },
  {
    value: "RS",
    label: "Serbia",
    dial_code: "+381",
    image: "/4x3/rs.svg",
  },
  {
    value: "SC",
    label: "Seychelles",
    dial_code: "+248",
    image: "/4x3/sc.svg",
  },
  {
    value: "SL",
    label: "Sierra Leone",
    dial_code: "+232",
    image: "/4x3/sl.svg",
  },
  {
    value: "SG",
    label: "Singapore",
    dial_code: "+65",
    image: "/4x3/sg.svg",
  },
  {
    value: "SX",
    label: "Sint Maarten (Dutch part)",
    dial_code: "+599",
    image: "/4x3/sx.svg",
  },
  {
    value: "SK",
    label: "Slovakia",
    dial_code: "+421",
    image: "/4x3/sk.svg",
  },
  {
    value: "SI",
    label: "Slovenia",
    dial_code: "+386",
    image: "/4x3/si.svg",
  },
  {
    value: "SB",
    label: "Solomon Islands",
    dial_code: "+677",
    image: "/4x3/sb.svg",
  },
  {
    value: "SO",
    label: "Somalia",
    dial_code: "+252",
    image: "/4x3/so.svg",
  },
  {
    value: "ZA",
    label: "South Africa",
    dial_code: "+27",
    image: "/4x3/za.svg",
  },
  {
    value: "GS",
    label: "South Georgia",
    dial_code: "+",
    image: "/4x3/gs.svg",
  },
  {
    value: "SS",
    label: "South Sudan",
    dial_code: "+211",
    image: "/4x3/ss.svg",
  },
  {
    value: "ES",
    label: "Spain",
    dial_code: "+34",
    image: "/4x3/es.svg",
  },
  {
    value: "LK",
    label: "Sri Lanka",
    dial_code: "+94",
    image: "/4x3/lk.svg",
  },
  {
    value: "SD",
    label: "Sudan",
    dial_code: "+249",
    image: "/4x3/sd.svg",
  },
  {
    value: "SR",
    label: "Suriname",
    dial_code: "+597",
    image: "/4x3/sr.svg",
  },
  {
    value: "SJ",
    label: "Svalbard and Jan Mayen",
    dial_code: "+47",
    image: "/4x3/sj.svg",
  },
  {
    value: "SZ",
    label: "Swaziland",
    dial_code: "+268",
    image: "/4x3/sz.svg",
  },
  {
    value: "SE",
    label: "Sweden",
    dial_code: "+46",
    image: "/4x3/se.svg",
  },
  {
    value: "CH",
    label: "Switzerland",
    dial_code: "+41",
    image: "/4x3/ch.svg",
  },
  {
    value: "SY",
    label: "Syrian Arab Republic",
    dial_code: "+963",
    image: "/4x3/sy.svg",
  },
  {
    value: "TW",
    label: "Taiwan, Province of China",
    dial_code: "+886",
    image: "/4x3/tw.svg",
  },
  {
    value: "TJ",
    label: "Tajikistan",
    dial_code: "+992",
    image: "/4x3/tj.svg",
  },
  {
    value: "TZ",
    label: "Tanzania",
    dial_code: "+255",
    image: "/4x3/tz.svg",
  },
  {
    value: "TH",
    label: "Thailand",
    dial_code: "+66",
    image: "/4x3/th.svg",
  },
  {
    value: "TL",
    label: "Timor-Leste",
    dial_code: "+670",
    image: "/4x3/tl.svg",
  },
  {
    value: "TG",
    label: "Togo",
    dial_code: "+228",
    image: "/4x3/tg.svg",
  },
  {
    value: "TK",
    label: "Tokelau",
    dial_code: "+690",
    image: "/4x3/tk.svg",
  },
  {
    value: "TO",
    label: "Tonga",
    dial_code: "+676",
    image: "/4x3/to.svg",
  },
  {
    value: "TT",
    label: "Trinidad and Tobago",
    dial_code: "+1-868",
    image: "/4x3/tt.svg",
  },
  {
    value: "TN",
    label: "Tunisia",
    dial_code: "+216",
    image: "/4x3/tn.svg",
  },
  {
    value: "TR",
    label: "Turkey",
    dial_code: "+90",
    image: "/4x3/tr.svg",
  },
  {
    value: "TM",
    label: "Turkmenistan",
    dial_code: "+993",
    image: "/4x3/tm.svg",
  },
  {
    value: "TC",
    label: "Turks and Caicos Islands",
    dial_code: "+1-649",
    image: "/4x3/tc.svg",
  },
  {
    value: "TV",
    label: "Tuvalu",
    dial_code: "+688",
    image: "/4x3/tv.svg",
  },
  {
    value: "UG",
    label: "Uganda",
    dial_code: "+256",
    image: "/4x3/ug.svg",
  },
  {
    value: "UA",
    label: "Ukraine",
    dial_code: "+380",
    image: "/4x3/ua.svg",
  },
  {
    value: "AE",
    label: "United Arab Emirates",
    dial_code: "+971",
    image: "/4x3/ae.svg",
  },
  {
    value: "GB",
    label: "United Kingdom",
    dial_code: "+44",
    image: "/4x3/gb.svg",
  },
  {
    value: "US",
    label: "United States",
    dial_code: "+1",
    image: "/4x3/us.svg",
  },
  {
    value: "UM",
    label: "U.S. Minor Islands",
    dial_code: "+1",
    image: "/4x3/um.svg",
  },
  {
    value: "UY",
    label: "Uruguay",
    dial_code: "+598",
    image: "/4x3/uy.svg",
  },
  {
    value: "UZ",
    label: "Uzbekistan",
    dial_code: "+998",
    image: "/4x3/uz.svg",
  },
  {
    value: "VU",
    label: "Vanuatu",
    dial_code: "+678",
    image: "/4x3/vu.svg",
  },
  {
    value: "VE",
    label: "Venezuela",
    dial_code: "+58",
    image: "/4x3/ve.svg",
  },
  {
    value: "VN",
    label: "Viet Nam",
    dial_code: "+84",
    image: "/4x3/vn.svg",
  },
  {
    value: "VG",
    label: "Virgin Islands, British",
    dial_code: "+1-284",
    image: "/4x3/vg.svg",
  },
  {
    value: "VI",
    label: "Virgin Islands, U.S.",
    dial_code: "+1-340",
    image: "/4x3/vi.svg",
  },
  {
    value: "WF",
    label: "Wallis and Futuna",
    dial_code: "+681",
    image: "/4x3/wf.svg",
  },
  {
    value: "YE",
    label: "Yemen",
    dial_code: "+967",
    image: "/4x3/ye.svg",
  },
  {
    value: "ZM",
    label: "Zambia",
    dial_code: "+260",
    image: "/4x3/zm.svg",
  },
  {
    value: "ZW",
    label: "Zimbabwe",
    dial_code: "+263",
    image: "/4x3/zw.svg",
  },
  {
    value: "AX",
    label: "Åland Islands",
    dial_code: "+358-18",
    image: "/4x3/ax.svg",
  },
];
